# Boilerplate for an autogenerated Kbase Agave CDM query app template

# This section will go away in ~2 months
# Fetch using cacheing version of iRODS iget
# i comes in as a path and we need to snag just the filename
iget_cached -fVT ${inputFile} .
INFILE=$(basename ${inputFile})

# Build ARGS variable
# Automatically emit a set of conditionals via bash logic
# Since these flags are mutually exclusive, we only allow one at a time
# in the ARGS variable
ARGS="-i ${INFILE}"
if [ -n "${c}" ]; then ARGS="-c ${c}"; fi
if [ -n "${fasta}" ]; then ARGS="--fasta ${fasta}"; fi

# Unpack kb/ directory
tar -zxf kb.tgz
echo "./kb" >> .iplant.archive

BIN_HOME="kb/deployment/bin"
BIN_NAME="contigs_to_sequences"

# Run application
set -x
$BIN_HOME/${BIN_NAME} ${ARGS} > stdout_${BIN_NAME}
set +x

# Clean up
rm -rf kb
